### ISSUE TITLE
files without empty line throws an error

### ISSUE THREAD

**Issue by PatrickJS** [erm0l0v/webpack-md5-hash#1]
see https://github.com/AngularClass/angular2-webpack-starter/issues/215#issuecomment-173515930 can you log a better error message to suggest having an empty new line

**Comment by erm0l0v** [comment]
Yes sure. I'll add error message.

**Comment by PatrickJS** [comment]
thanks!

**Comment by dsebastien** [comment]
+1, I'd like to see which file causes the issue as I'm left in the dark with the error

**Comment by jsec516** [comment]
Is there any quick solve for that issue?

**Comment by PatrickJS** [comment]
@erm0l0v more developers are running into this problem so it would be great to either show the file in question or allow files without the newline

**Comment by dsebastien** [comment]
I'm looking at the code trying to reproduce the issue but I'm a bit lost ;-)

**Comment by dsebastien** [comment]
I think I've got it. It's possible to pass an initialValue to the reduce function: http://es5.github.io/#x15.4.4.21

With it I think the issue will be fixed.

**Comment by dsebastien** [comment]
I've created a PR for this: https://github.com/erm0l0v/webpack-md5-hash/pull/2

**Comment by erm0l0v** [comment]
Sorry for delay, guys.
 @dsebastien thanks for PR.

I published version 0.0.5. Could you test this with your code?

**Comment by dsebastien** [comment]
I've tested it against angular2-webpack-starter and it seems okay now, thanks!

**Comment by erm0l0v** [comment]
Cool!
