### ISSUE TITLE
Bundle md5sum does not match file output md5

### ISSUE THREAD

**Issue by damons-sportsbet** [erm0l0v/webpack-md5-hash#3]
Hi, when I use this plugin to generate a js bundle the md5 sum in the filename does not match what I get when I run md5sum on the bundle. Here is my webpack plugin:

`var HtmlWebpackPlugin = require('html-webpack-plugin');
var WebpackMd5Hash = require('webpack-md5-hash');

config = {
    entry: './src/app.tsx',

```
output: {
    path: 'dist',
    filename: 'bundle.[chunkhash].[id].js'
},
plugins: [
    new HtmlWebpackPlugin({
        template: './web/index.html'
    }),
    new WebpackMd5Hash()

],
resolve: {
    extensions: ['', '.js', '.ts', '.tsx']
},
module: {
    loaders: [
        { 
            test: /\.tsx?$/, 
            exclude: /node_modules/,
            loaders: ['ts-loader'] 
        }
    ]
}
```

}

module.exports = config;`

which outputs a file called:
bundle.04848911b5e746ce241d.0.js

but when I run md5sum on that file I get:
22f08596b2387e592bf4eb807765579d  bundle.04848911b5e746ce241d.0.js

why would this be the case?

Also, I understand md5 hashes are always 32 characters (128 bits encoded as hexadecimal) so why is the bundle hash only 20 characters long?

thanks,

Damon

**Comment by erm0l0v** [comment]
Hi, @damon-at-sportsbet Thank you for your request.

_WebpackMd5Hash_ affect only on chunk files (not entrypoints)

> e.g. files that loaded in [runtime](https://webpack.github.io/docs/code-splitting.html#defining-a-split-point)

If you use _webpack_ >= 1.6.0 You can specify custom hash function in config
`output: {hashFunction: 'md5', hashDigestLength: 32}`

`hashDigestLength` - required to avoid [hash cutting](https://github.com/webpack/webpack/blob/v1.6.0/lib/Compilation.js#L739)

**Comment by damons-sportsbet** [comment]
Thanks! I guess all I really needed to know was the concept of hash cutting. I can now successfully generate chunks and verify their md5s. Great work on the plugin too, it works really nicely.
